#문제 1
## 1부터 n까지의 합 구하기

알고리즘은 주어진 문제를 풀기 위한 절차나 방법. 알고리즘이 있으려면 반드시 문제가 필요하다. 

여기서 문제는 '1부터 n까지 연속한 숫자의 합 구하기'이다. 

입력: n까지
출력: n=10이면 출력은 55

구체적인 알고리즘:
1. 합을 기록할 변수 s를 만들고 0을 저장
2. 변수 i를 만들어 1부터 n까지의 숫자를 1씩 증가시키며 반복
3. 기존의 s에 i를 더하여 얻은 값을 다시 s에 저장
4. 반복이 끝났을때 s에 저장된 값이 결과값.

In [1]:
# 내 답
n = int(input())
a = 0

for i in range(0, n+1):
  a += i

print(a)

4
10

In [3]:
# 책의 답 1 (함수로 구현)

def sum_n(n):
  s = 0
  for i in range(1, n+1):
    s = s+i
  return s

print(sum_n(10))

55

In [4]:
# 책의 답 2

def sum_n(n):
  return n*(n+1)//2 #//은 나누기

print(sum_n(10))

55

**계산 복잡도** : 어떤 알고리즘이 문제를 풀기 위해 해야하는 계산이 얼마나 복잡한지 나타낸정도.

표기법: O(n)

첫번째 알고리즘은 입력크기 n에 대해 사칙 연산을 n번해야 된다 --> O(n)

두번째 알고리즘은 입력크기 n과 무관하게 사칙연산을 세번해야 한다. --> O(1)
(입력크기가 커져도 계산이 더 늘어나지 않는다면 모두 0(1))

**O(n)**: 필요한 계산횟수가 입력크기 n과 비례할 때

**O(1)**: 필요한 계산횟수가 입력크기 n과 무관할 때

In [7]:
# 연습문제 1-1
# 1부터 n까지 연속한 숫자의 제곱의 합을 구해라.

def double_sum(n):
  a = 0
  for i in range(0, n+1):
    a += i**2 #제곱은 **
  return a 

print(double_sum(10))

385

In [8]:
# 연습문제 1-2
# 연습문제 1-1 프로그램의 계산 복잡도는 O(1)과 O(n) 중 무엇일까요?
print("O(1)")

O(1)

In [11]:
# 연습문제 1-3
# 1부터 n까지 연속한 숫자의 제곱의 합을 구하는 공식은  로 알려져 있습니다. for 반복문 대신 이 공식을 이용하면 알고리즘의 계산 복잡도는 O(1)과 O(n) 중 무엇이 될까요?

def double_sum(n):
  return n*(n+1)*(2*n+1)//6

print(double_sum(10))

385

# 문제 2
## 최댓값 찾기
주어진 숫자 n개 중 가장 큰 숫자를 찾는 알고리즘을 만들어보자.

최댓값 찾는 알고리즘:
1. 첫번째 숫자 17을 최댓값으로 기억
2. 두번째 숫자 92를 현재 최댓값 17과 비교
3. 세번째 숫자 18을 현재 최댓값 92와 비교
4. ~7. 반복
8. 마지막 숫자를 현재 최댓값 92와 비교
9. 마지막으로 기억된 92가 주어진 숫자중 최댓값

**리스트**
리스트는 정보 여러개를 하나로 묶어 저장하고 관리할 수 있는 기능. 

len(a) - 리스트 길이 구하기

append(x) - 자료x를 리스트의 맨 뒤에 추가

insert(i, x) - 리스트의 i번 위치에 x를 추가

pop(i) - i번 위치에 있는 자료를 리스트에서 빼내면서 그 값을 함수의 결괏값으로 돌려준다.

clear() - 리스트의 모든 자료를 지운다

x in a - 어떤 자료 x가 리스트 a안에 있는지 확인

In [15]:
# 내 답
list = [17, 92, 18, 33, 58, 7, 33, 42]
max = list[0]
for i in list:
  if max < i:
    max = i
  else: 
    pass

print(max)

92

In [16]:
# 책 답
def find_max(a):
  n = len(a)
  max_v = a[0]

  for i in range(1, n):
    if a[i] > max_v:
      max_v = a[i]

  return max_v

v = [17, 92, 18, 33, 58, 7, 33, 42]
print(find_max(v))

92

In [20]:
# 응용
# 리스트에 숫자가 n개 있을 때 가장 큰 값이 있는 위치 번호를 돌려주는 알고리즘을 만들어 보세요.

def list_num(a):
  n = len(a)
  max = a[0]

  for i in range(1, n):
    if a[i] > max:
      max = a[i]
      list_num = i
  return list_num

v = [17, 18, 33, 58, 7, 33, 92, 42]
print(list_num(v))

6

In [19]:
# 책 닶

def find_max_idx(a):
  n = len(a)
  max_idx = 0
  for i in range(1, n):
    if a[i] > a[max_idx]:
      max_idx = i

  return max_idx

v = [17, 92, 18, 33, 58, 7, 33, 42]
print(find_max_idx(v))

1

In [22]:
# 연습문제
# 숫자 n개를 리스트로 입력받아 최솟값을 구하는 프로그램을 만들어 보세요.

def min_list(a):
  n = len(a)
  min = a[0]

  for i in range(0, n):
    if min > a[i]:
      min = a[i]

  return min

v = [17, 92, 18, 33, 58, 7, 33, 42]
print(min_list(v))

7

# 문제 3
## 동명이인 찾기 1

n명의 사람 이름 중에서 같은 이름을 찾아 집합으로 만들어 돌려주는 알고리즘을 만들어 보세요.

동명이인을 찾는 알고리즘:
1. 첫번째 tom을 뒤에 있는 jerry, mike, tom과 차례로 비교.
2. 첫번째 tom과 마지막 tom이 같으므로 동명이인이다.
3. 두번째 jerry를 뒤에있는 mike, tom과 비교
4. 세번째 mike를 뒤에 있는 tom과 비교.
5. 마지막 tom은 비교하지 않아도 된다
6. 같은 이름은 tom 하나뿐이다

집합

집합은 리스트와 같이 정보를 여러개 넣어서 보관할 수 있는 파이썬의 기능.
다만 집합 하나에는 같은 자료가 중복되어 들어가지 않고, 자료의 순서도 의미가 없다는 것이 리스트와 다르다.

s = set()

len(s) - 집합의 길이 구하기

add(x) - 집합에 자료 x 추가

discard(x) - 집합에 자료 x가 들어있다면 삭제

clear() - 집합의 모든 자료를 지운다.

x in s - 어떤 자료 x가 집합 s에 들어있는지 확인한다.

In [33]:
# 내 답

def find_name(x):
  n = len(x)
  name = x[0]

  for i in range(1, n):
    if name == x[i]:
      name = x[i]
  return name

v = ["Sugar", "Tom", "Jerry", "Mike", "Tom"]
print(find_name(v))

Sugar

In [31]:
# 책 답

def find_same_name(a):
  n = len(a)
  result = set() #결과를 저장할 집합
  
  for i in range(0, n-1):
    for j in range(i+1, n):
      if a[i] == a[j]:
        result.add(a[i])

  return result

name = ["Tom", "Jerry", "Mike", "Tom"]
print(find_same_name(name))

{'Tom'}

In [37]:
# 연습문제 1
# n명 중 두명을 뽑아 짝을 짓는다고 할 때 짝을 지을 수 있는 모든 조합을 출력하는 알고리즘을 만들어보세요

def make_friends(a):
  friends = set()
  n = len(a)
  for i in range(0, n-1):
    for j in range(i+1, n):
      friends.add(a[i] + " - " + a[j])
  return friends

a = ["Tom", "Jerry", "Mike"]
print(make_friends(a))

{'Jerry - Mike', 'Tom - Mike', 'Tom - Jerry'}

In [38]:
# 연습문제 2-1
print("O(1)")
print("O(n)")
print("O(1)")
print("0(n)")

O(1)
O(n)
O(1)
0(n)